### ISSUE TITLE
How to set the animation inside a tableviewcell?

### ISSUE THREAD

**Issue by shravansukumar** [sanjaymhj/SMRippleExample#1]
Hello,
Thanks for the ripple effect, When using it in a normal view, the frame for the animation gets set properly. i.e., when I centre the ripple effect with a view of fixed dimensions. But when I try to do this inside of `tableviewcell`, the frames for the ripple are not getting set properly. They start the effect at haphazard spots. I'm setting up the effect in the `willDisplay: cell` tableView method. Is there something more I should add while setting it up for using it with a `tableviewcell`?
Thanks.

**Comment by sanjaymhj** [comment]
I've change the code a bit and tested for the table view cell. Here's the result I did.

![TableViewCell ripple](http://i.imgur.com/6QXngIt.png)
Code for ripple in cell is in the repo.

Hope the change solves your requirement. :)
P.S. Be careful while adding ripple/layer in cell(It causes more problems)

**Comment by shravansukumar** [comment]
Hello,
Thanks for making the changes, but still it is not working properly for me. I've added a link to my repo [here](https://github.com/shravansukumar/RippleEffectTest), Please do go through it and tell if I'm making any mistake. 
Thanks.

UPDATE: When I run it on a 5s, it seems to work fine. The problem arises when using it in the 6s, the ripple view is a bit distorted towards the left.

**Comment by sanjaymhj** [comment]
@shravansukumar Sorry for very late reply... Please have a look at the code in RippleCell.
